spring.application.name=MarketPlace
spring.datasource.url=jdbc:postgresql://localhost:5432/MarketPlace
spring.datasource.username=postgres
spring.datasource.password=passwordSecret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
springdoc.swagger-ui.path=/swagger-ui.html